### ISSUE TITLE
Fix hardcoded es operator image name in openshift deployment template

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/elasticsearch-operator#5] opened 2018-10-02 13:57 UTC
I think we need to get rid of hardcoded value in `deploy/openshift/elasticsearch-template.yaml`:

https://github.com/openshift/elasticsearch-operator/blob/d1859997f572708e3602ac8a8930f72c2b76befa/deploy/openshift/elasticsearch-template.yaml#L28

Currently it is set to `image: t0ffel/es-operator` and if I understand correctly to make this work it is required to manually modify `Makefile` as it does not set `$(DOCKER_TAG)` from outside:

https://github.com/openshift/elasticsearch-operator/blob/d1859997f572708e3602ac8a8930f72c2b76befa/Makefile#L41

**Comment by ewolinetz** [comment] 2018-10-02 16:50
That is just an update to the operator deployment object, that shouldn't be too difficult to update once we have our new operator image. With the cluster-logging-operator I'm trying to limit the amount of granular control that a user would have over image versions since we would want to lock step configurations and image versions.

**Comment by jcantrill** [comment] 2018-12-10 19:17
This is an issue in master.  We should modify to match https://github.com/openshift/cluster-logging-operator/pull/33/files#diff-a1597e288a8b8ede15888443903d9d28R31 so that it fits with the existing release process.  Additionally, this allows the operator to function independent of cluster-logging-operator

**Comment by ewolinetz** [comment] 2018-12-10 20:09
This issue is related to the elasticsearch operator on its deployment. The value has been updated, though we should investigate removing them from the `deploy` directory as its a duplicate of what is in `manifests`.

Closing this as resolved. Will open another issue to track the removal of duplicate deployment.

**Closed by ewolinetz** 2018-12-10 20:09 UTC
