### ISSUE TITLE
Lack of fsGroup in ClusterLogging CRD.

### ISSUE THREAD

**Issue by DTadrzak** [openshift/elasticsearch-operator#245] opened 2020-02-20 15:22 UTC
Hey,
It looks like CRD of ClusterLogging does not allow us to define `fsGroup` (https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/pod_security_context.html#fsgroup).

 It huge gap due to the fact that by default CSI creates volume with root as owner whereas the user used inside elasticsearch container is created with uid: 1000. It means that all clusters, deployed with storageClass provided by CSI will raise the following error: 

> main ERROR Unable to create file 
/elasticsearch/persistent/elasticsearch/logs/elasticsearch.log java.io.IOException: Could not create directory /elasticsearch/persistent/elasticsearch/logs

 due to the insufficient privileges on PV.

**Comment by ewolinetz** [comment] 2020-03-03 19:17
This was done by design to remove any volume specific configurations. The recommended fix for this is to create a different storageClass for Elasticsearch to use and specify that on your CR. The out of the box `gp2` storageClass should work also.

**Comment by meshistern** [comment] 2020-05-20 12:30
Hey,
I am having the same problem when i am trying to deploy ClusterLogging  on azure using the azure-rwo and managed-premium storageClasses. What can i do?

**Closed** 2020-12-12 16:14 UTC
Labels: lifecycle/rotten
